# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-12 16:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RNA_alias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=128, unique=True)),
                ('source', models.TextField()),
                ('rna', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.RNA')),
            ],
        ),
    ]
