# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-12 16:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_rna_alias'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RNA_alias',
            new_name='RNAalias',
        ),
    ]
