# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-13 20:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_auto_20160712_1809'),
    ]

    operations = [
        migrations.AddField(
            model_name='rnaalias',
            name='votes',
            field=models.IntegerField(default=0),
        ),
    ]
