# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-22 14:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0004_rnaalias_votes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Protein',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=128, unique=True)),
                ('views', models.IntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='interaction',
            name='entity1',
        ),
        migrations.RemoveField(
            model_name='interaction',
            name='entity2',
        ),
        migrations.AddField(
            model_name='interaction',
            name='score',
            field=models.DecimalField(decimal_places=5, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='interaction',
            name='type',
            field=models.CharField(choices=[('Co', 'Combined'), ('Cu', 'Curated'), ('Ex', 'Experiments'), ('Pr', 'Predictions'), ('Te', 'Textmining')], max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='rna',
            name='interactions',
            field=models.ManyToManyField(to='portal.Interaction'),
        ),
        migrations.AddField(
            model_name='protein',
            name='interactions',
            field=models.ManyToManyField(to='portal.Interaction'),
        ),
    ]
